config/routes.rb
Rails.application.routes.draw do
  # show all profiles
  get 'profiles' => 'profiles#index'
  # whatever is in spot is the id, shows 1 profile
  get 'profiles/:id' => "profiles#show", as: :profile

 resources :tweets

  devise_for :users

  root 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  # validations
  # message is present and no blank tweets
  # less than 140
  validates :message, presence: true, length: { maximum: 140, too_long: 'a tweet is only 140 characters max'}
  # no blank user id
  validates :user_id, presence: true
  # and has to be real user
  validates :user, presence: true
end

# == Schema Information
#
# Table name: tweets
#
#  id         :integer          not null, primary key
#  message    :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_tweets_on_user_id  (user_id)
#

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets

# user validations
# require name and username

# name has to be unique
validates :name, presence: true
validates :username, presence: true, uniqueness: true

end


# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  username               :string
#  bio                    :text
#  location               :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_user_parameters, if: :devise_controller?

  protected

  def configure_permitted_user_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name, :username, :bio, :location) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :name, :username, :bio, :location) }
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    # all the user's profiles
    @users = User.all
  end

  def show
    # individual profile
    @user = User.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: [:edit, :show, :update, :destroy]


  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: "save successful!"}
        else
        format.html { render :new }
      end
    end
  end

  def edit
    # get tweet we wanna edit and send it to the view
    # happens w/ before action
    # before action gets the tweet we wanna show
  end

  def update
    # get new params we want to update - from before action

    # update it with new info from params
    # save it
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "you changed that tweet!"}
      else
        format.html { render :edit }
      end
     end
   end

  def show
    # setup to show latest tweet from user
    # before action gets tweet we wanna show
  end

  def destroy
    # get the tweet (before action gets tweet)
    # destroy the tweet
    @tweet.destroy
    # re render index view
    respond_to do |format|
      format.html {redirect_to tweets_url, notice: 'tweet deleted succuessfully'}
    end
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>People's Posting App!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- login/out button -->
    <%= link_to 'logout', destroy_user_session_path, method: :delete, class: 'btn btn-xs btn-default' %>
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<h1>all users</h1>

<% @users.each do |user| %>
  <%= link_to user.username, profile_path(user) %> <br>
<% end %>

app/views/profiles/show.html.erb
<!-- username -->
<h1><%= @user.username %>'s profile</h1>

<!-- show tweets -->

<% @user.tweets.each do |tweet| %>
  <%= tweet.message %> <br>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
<!-- show any errors -->
<% if @tweet.errors.any? %>
  <div id="error_explaination">
    <h2>
      <%= pluralize(@tweet.errors.count, 'error') %> prohibited this tweet from being saved:
    </h2>
    <!-- interate thru errors -->
    <ul>
      <% @tweet.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- actual form -->

  <!-- message field -->
  <div class="field form-group">
    <%= f.label :message %> <br>
    <%= f.text_field :message, class: 'form-control' %>
  </div>

  <!-- user id field - current user id sets the id for user -->
  <div class="field form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <!-- submit button -->
  <div class="actions form-group">
    <%= f.submit class: 'btn btn-sm btn-default' %>
  </div>

<% end %>

app/views/tweets/edit.html.erb
<h1>edit</h1>

<%= render 'form' %>


<%= link_to 'back to feed', tweets_path, class: 'btn btn-sm btn-default' %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<!-- make a new tweet -->
<%= link_to 'new tweet', new_tweet_path, class: 'btn btn-md btn-success' %>

<!-- see all tweets in a table -->
<table class="table table-striped table-hover">
<!-- head -->
  <thead>
    <tr>
      <th>message</th>
      <th>username</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<!-- body -->
  <tbody>
  <!-- iterate through the tweets each one in a new row -->
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= tweet.user.username %></td>
        <td><%= link_to 'show', tweet %></td>
        <td><%= link_to 'edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'destroy', tweet, method: :delete, data: {confirm: 'u sure???'} %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/tweets/new.html.erb
<h1>new tweet</h1>

<%= render 'form' %>


<!-- back to index -->

<%= link_to 'back to feed', tweets_path, class: 'btn btn-sm btn-default' %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<!-- tweet -->

  <!-- username -->
  <p>
    <strong>user: </strong><%= @tweet.user.username %>
  </p>

  <!-- message -->
  <p>
    <strong>message: </strong><%= @tweet.message %>
  </p>

  <!-- created at what time -->
  <p>
    <strong>tweeted at: </strong><%= @tweet.created_at %>
  </p>

<!-- button to edit -->
<%= link_to 'edit', edit_tweet_path(@tweet), class: 'btn btn-sm btn-default' %>

<!-- go back to index -->
<%= link_to 'back to feed', tweets_path, class: 'btn btn-sm btn-default' %>